config/routes.rb
Blog::Application.routes.draw do
  
  resources :feedback_messages

  devise_for :users

 

root :to => 'home#index'

end

app/models/feedback_message.rb
class FeedbackMessage < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_local
  def set_local
 I18n.locale = extract_locale_from_accept_language_header

  end

  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first


  end
end

app/controllers/feedback_messages_controller.rb
class FeedbackMessagesController < ApplicationController
  # GET /feedback_messages
  # GET /feedback_messages.json
  def index
    @feedback_messages = FeedbackMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedback_messages }
    end
  end

  # GET /feedback_messages/1
  # GET /feedback_messages/1.json
  def show
    @feedback_message = FeedbackMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback_message }
    end
  end

  # GET /feedback_messages/new
  # GET /feedback_messages/new.json
  def new
    @feedback_message = FeedbackMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback_message }
    end
  end

  # GET /feedback_messages/1/edit
  def edit
    @feedback_message = FeedbackMessage.find(params[:id])
  end

  # POST /feedback_messages
  # POST /feedback_messages.json
  def create
    @feedback_message = FeedbackMessage.new(params[:feedback_message])

    respond_to do |format|
      if @feedback_message.save
        format.html { redirect_to @feedback_message, notice: 'Feedback message was successfully created.' }
        format.json { render json: @feedback_message, status: :created, location: @feedback_message }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedback_messages/1
  # PUT /feedback_messages/1.json
  def update
    @feedback_message = FeedbackMessage.find(params[:id])

    respond_to do |format|
      if @feedback_message.update_attributes(params[:feedback_message])
        format.html { redirect_to @feedback_message, notice: 'Feedback message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedback_messages/1
  # DELETE /feedback_messages/1.json
  def destroy
    @feedback_message = FeedbackMessage.find(params[:id])
    @feedback_message.destroy

    respond_to do |format|
      format.html { redirect_to feedback_messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end

  def new_feedback
 @feedback_message = FeedbackMessage.new
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_messages_helper.rb
module FeedbackMessagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/feedback_messages/_form.html.erb
<%= form_for(@feedback_message) do |f| %>
  <% if @feedback_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback_message.errors.count, "error") %> prohibited this feedback_message from being saved:</h2>

      <ul>
      <% @feedback_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.text_field :email %> <br/>
    <%= f.text_field :subject %> <br/>
    <%= f.text_field :body %> <br/>
    <%= f.submit %>
  </div>
<% end %>

app/views/feedback_messages/edit.html.erb
<h1>Editing feedback_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback_message %> |
<%= link_to 'Back', feedback_messages_path %>

app/views/feedback_messages/index.html.erb
<h1>Listing feedback_messages</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Subject</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedback_messages.each do |feedback_message| %>
  <tr>
    <td><%= feedback_message.subject %></td>
    <td><%= feedback_message.email %></td>
    <td><%= feedback_message.subject %></td>
    <td><%= feedback_message.body %></td>
    <td><%= link_to 'Show', feedback_message %></td>
    <td><%= link_to 'Edit', edit_feedback_message_path(feedback_message) %></td>
    <td><%= link_to 'Destroy', feedback_message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback message', new_feedback_message_path %>

app/views/feedback_messages/new.html.erb
<h1>New feedback_message</h1>

<%= render 'form' %>

<%= link_to 'Back', feedback_messages_path %>

app/views/feedback_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @feedback_message.email %>
</p>

<p>
  <b>Subject:</b>
  <%= @feedback_message.subject %>
</p>


  <b>Body:</b>
  <%= @feedback_message.body %>



<%= link_to 'Edit', edit_feedback_message_path(@feedback_message) %> |
<%= link_to 'Back', feedback_messages_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/new_feedback.html.erb
<%= form_for @feedback_message do |f| %>
<%= f.text_field :email %>
<%= f.text_field :subject %>
<%= f.text_field :body %>
<%= f.submit t("send") %>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>huidige taal: <%= I18n.locale %></p>
<p class="notice"><%= notice %></p>
<p class=alert"><%= alert %></p>
  <% if current_user %>
  <%= link_to t("logout"),destroy_user_session_path, :method => :delete %>

    <% end -%>

<%= link_to "feedback", new_feedback_message_path %>

  <%= yield %>

</body>
</html>